export const essentialAssets = {
  "avatar-placeholder": "/avatar-placeholder.webp",
  subscribe_tapsmart: "/subscribe_tapsmart.webp",
  battles: "/battles.webp",
  book: "/book.webp",
  friends: "/friends.webp",
  leaders: "/leaders.webp",
  market: "/market.webp",
  tasks: "/tasks.webp",
  swords: "/swords.webp",
  telegram: "/telegram.webp",
  "telegram-premium": "/telegram-premium.webp",
  "tutorial-0": "/tiger-bg.webp",
  "tutorial-1": "/tiger-bg1.webp",
  "tutorial-2": "/tiger-bg2.webp",
  avatar1: "/profile-avatar-placeholder.webp",
  level: "/level-arrow.webp",
  cup: "/cup.webp",
  loader: "/loader.svg",
  mech_1: "/mechanic_1.svg",
  mech_2: "/mechanic_2.svg",
  mech_3: "/mechanic_3.svg",
  mech_4: "/mechanic_4.svg",
  mech_5: "/mechanic_5.svg",
  mech_6: "/mechanic_6.svg",
  mech_7: "/mechanic_7.svg",
  mech_placeholder: "/mechanic_placeholder.svg",
  congrats: "/congrats.webp",
  x2: "/x2.webp",
  winner_token: "/winner_token.webp",
  repetition: "/repetition.webp",
  stories: "/stories.webp",
  "1st_place": "/1st_place.webp",
  "2nd_place": "/2nd_place.webp",
  "3rd_place": "/3rd_place.webp",
  mult: "/mult.svg",
  new_level: "/new_level.webp",
  new_league: "/new_league.webp",
  rays_purple: "/rays_purple.webp",
  bolt_earned: "/bolt_earned.webp",
  arrow_right: "/arrow_right.webp",
  play_battle: "/play_battle.webp",
  pass_exam: "/pass_exam.webp",
  clock: "/clock.webp",
  times: "/times.webp",
  tapsmart_title: "/tapsmart_title.webp",
  battle_results_final: "/battle_results_final.webp",
  status_completed: "/status_completed.webp",
  subscribe_telegram: "/subscribe_telegram.webp",
  score: "/score.webp",
  leaderboard_1st: "/leaderboard_1st.webp",
  leaderboard_2nd: "/leaderboard_2nd.webp",
  leaderboard_3rd: "/leaderboard_3rd.webp",
  rocket: "/rocket.webp",
  ton: "/ton.webp",
  cart: "/cart.webp",
  confirm: "/confirm.webp",
  prize_fund: "/prize_fund.webp",
  ask_feedback: "/ask_feedback.webp",
  "player-marker": "/player-marker.webp",
  check: "/check.webp",
  present: "/present.webp",
  prize_bg: "/prize/prize-bg.webp",
  prize_nut: "/prize/prize-nut.webp",
  prize_present: "/prize/prize-present.webp",
  prize_rays: "/prize/prize-rays.webp",
  prize_star: "/prize/prize-star.webp",
  prize_ton: "/prize/prize-ton.webp",
  stars: "/stars.webp",
  user: "/user.webp",
  add_home_screen: "/add_home_screen.webp",
  invite_friends: "/invite_friends.webp",
};

export const nonEssentialAssets = {};

// assets folder
export const assets = {
  copy: "assets/icons/copy.svg",
  bolt: "assets/icons/bolt.svg",
  "bolt-dark": "assets/icons/bolt-dark.svg",
  energy: "assets/icons/energy.svg",
  nut: "assets/icons/nut.svg",
  league: "assets/icons/league.svg",
  refresh: "assets/icons/refresh.svg",
  "chevron-right": "assets/icons/chevron-right.svg",
  "enemy-marker": "assets/icons/enemy-marker.svg",
  friend: "assets/icons/friend.svg",
};

export const sounds = {
  // soundtrack: "/soundtrack.mp3",
};

export const fonts = {
  // FiraSansRegular: {
  //   src: "assets/fonts/fira-sans/fira-sans-v17-cyrillic_latin-regular.woff2",
  //   weight: 400,
  // },
  // FiraSansSemibold: {
  //   src: "assets/fonts/fira-sans/fira-sans-v17-cyrillic_latin-600.woff2",
  //   weight: 600,
  // },
  // FiraSansBold: {
  //   src: "assets/fonts/fira-sans/fira-sans-v17-cyrillic_latin-700.woff2",
  //   weight: 700,
  // },
  // FiraSansBlack: {
  //   src: "assets/fonts/fira-sans/fira-sans-v17-cyrillic_latin-900.woff2",
  //   weight: 900,
  // },
  // FiraSansCondensedRegular: {
  //   src: "assets/fonts/fira-sans-condensed/fira-sans-condensed-v10-cyrillic_latin-regular.woff2",
  //   weight: 400,
  // },
  // FiraSansCondensedBold: {
  //   src: "assets/fonts/fira-sans-condensed/fira-sans-condensed-v10-cyrillic_latin-700.woff2",
  //   weight: 700,
  // },
  // Exo2Regular: {
  //   src: "assets/fonts/exo2/exo-2-v21-latin-regular.woff2",
  //   weight: 400,
  // },
  // Exo2Bold: {
  //   src: "assets/fonts/exo2/exo-2-v21-latin-700.woff2",
  //   weight: 700,
  // },
  // Exo2Black: {
  //   src: "assets/fonts/exo2/exo-2-v21-latin-900.woff2",
  //   weight: 900,
  // },
};
